export interface HeroBannerSlide {
  id: number;
  title: string;
  subtitle: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  image: string;
  alt: string;
  discount?: string;
  backgroundColor: string;
  textColor: string;
  priority?: boolean; // 첫 번째 이미지 우선 로딩
  // i18n keys (optional, fallback to above strings if missing)
  titleKey?: string;
  subtitleKey?: string;
  descriptionKey?: string;
  buttonTextKey?: string;
  altKey?: string;
  discountKey?: string;
}

export const heroBannerSlides: HeroBannerSlide[] = [
  {
    id: 1,
    title: "신상품 런칭 기념",
    subtitle: "보고핏 여름 컬렉션",
    description: "시원하고 편안한 운동복으로 완벽한 여름을 준비하세요",
    buttonText: "지금 쇼핑하기",
    buttonLink: "/products?badge=NEW",
    image: "/hero/image1.png",
    alt: "보고핏 여름 컬렉션 신상품",
    discount: "최대 50%",
    backgroundColor: "",
    textColor: "text-gray-900",
    priority: true,
  titleKey: "hero.slides.1.title",
  subtitleKey: "hero.slides.1.subtitle",
  descriptionKey: "hero.slides.1.description",
  buttonTextKey: "hero.slides.1.buttonText",
  altKey: "hero.slides.1.alt",
  discountKey: "hero.slides.1.discount",
  },
  {
    id: 2,
    title: "타임세일 진행중",
    subtitle: "베스트셀러 특가전",
    description: "인기 상품들을 특별가로 만나보세요",
    buttonText: "특가 상품 보기",
    buttonLink: "/products?badge=SALE",
    image: "/hero/image2.png",
    alt: "베스트셀러 특가전 상품",
    discount: "50% OFF",
    backgroundColor: "",
    textColor: "text-gray-900",
  titleKey: "hero.slides.2.title",
  subtitleKey: "hero.slides.2.subtitle",
  descriptionKey: "hero.slides.2.description",
  buttonTextKey: "hero.slides.2.buttonText",
  altKey: "hero.slides.2.alt",
  discountKey: "hero.slides.2.discount",
  },
  {
    id: 3,
    title: "멤버십 혜택",
    subtitle: "무료배송 + 적립금",
    description: "회원가입하고 다양한 혜택을 받아보세요",
    buttonText: "회원가입하기",
    buttonLink: "/register",
    image: "/hero/image3.png",
    alt: "멤버십 혜택 안내",
    backgroundColor: "",
    textColor: "text-gray-900",
  titleKey: "hero.slides.3.title",
  subtitleKey: "hero.slides.3.subtitle",
  descriptionKey: "hero.slides.3.description",
  buttonTextKey: "hero.slides.3.buttonText",
  altKey: "hero.slides.3.alt",
  },
  {
    id: 4,
    title: "트렌드 룩북",
    subtitle: "스타일링 가이드",
    description: "이번 시즌 트렌드 아이템으로 완성하는 퍼펙트 룩",
    buttonText: "룩북 보기",
    buttonLink: "/category/lookbook",
    image: "/hero/image4.png",
    alt: "트렌드 룩북 스타일링",
    backgroundColor: "",
    textColor: "text-gray-900",
  titleKey: "hero.slides.4.title",
  subtitleKey: "hero.slides.4.subtitle",
  descriptionKey: "hero.slides.4.description",
  buttonTextKey: "hero.slides.4.buttonText",
  altKey: "hero.slides.4.alt",
  },
  {
    id: 5,
    title: "브랜드 스토리",
    subtitle: "보고핏의 철학",
    description: "건강한 라이프스타일을 위한 프리미엄 스포츠웨어",
    buttonText: "브랜드 알아보기",
    buttonLink: "/about",
    image: "/hero/image5.png",
    alt: "보고핏 브랜드 스토리",
    backgroundColor: "",
    textColor: "text-gray-900",
  titleKey: "hero.slides.5.title",
  subtitleKey: "hero.slides.5.subtitle",
  descriptionKey: "hero.slides.5.description",
  buttonTextKey: "hero.slides.5.buttonText",
  altKey: "hero.slides.5.alt",
  },
  {
    id: 6,
    title: "AI 피팅 서비스",
    subtitle: "가상 착용 체험",
    description: "AI로 미리 입어보고 완벽한 사이즈를 찾아보세요",
    buttonText: "가상 피팅하기",
    buttonLink: "/virtual-fitting",
    image: "/hero/image6.png",
    alt: "AI 가상 피팅 서비스",
    backgroundColor: "",
    textColor: "text-gray-900",
  titleKey: "hero.slides.6.title",
  subtitleKey: "hero.slides.6.subtitle",
  descriptionKey: "hero.slides.6.description",
  buttonTextKey: "hero.slides.6.buttonText",
  altKey: "hero.slides.6.alt",
  },
  // {
  //   id: 7,
  //   title: "신상품 런칭 기념",
  //   subtitle: "보고핏 여름 컬렉션",
  //   description: "시원하고 편안한 운동복으로 완벽한 여름을 준비하세요",
  //   buttonText: "지금 쇼핑하기",
  //   buttonLink: "/products?badge=NEW",
  //   image: "/hero/image7.png",
  //   alt: "보고핏 여름 컬렉션 신상품",
  //   discount: "최대 50%",
  //   backgroundColor: "",
  //   textColor: "text-gray-900",
  // priority: true,
  // titleKey: "hero.slides.1.title",
  // subtitleKey: "hero.slides.1.subtitle",
  // descriptionKey: "hero.slides.1.description",
  // buttonTextKey: "hero.slides.1.buttonText",
  // altKey: "hero.slides.1.alt",
  // discountKey: "hero.slides.1.discount",
  // },
  // {
  //   id: 8,
  //   title: "타임세일 진행중",
  //   subtitle: "베스트셀러 특가전",
  //   description: "인기 상품들을 특별가로 만나보세요",
  //   buttonText: "특가 상품 보기",
  //   buttonLink: "/products?badge=SALE",
  //   image: "/hero/image8.png",
  //   alt: "베스트셀러 특가전 상품",
  //   discount: "50% OFF",
  //   backgroundColor: "",
  // textColor: "text-gray-900",
  // titleKey: "hero.slides.2.title",
  // subtitleKey: "hero.slides.2.subtitle",
  // descriptionKey: "hero.slides.2.description",
  // buttonTextKey: "hero.slides.2.buttonText",
  // altKey: "hero.slides.2.alt",
  // discountKey: "hero.slides.2.discount",
  // },
  // {
  //   id: 9,
  //   title: "멤버십 혜택",
  //   subtitle: "무료배송 + 적립금",
  //   description: "회원가입하고 다양한 혜택을 받아보세요",
  //   buttonText: "회원가입하기",
  //   buttonLink: "/register",
  //   image: "/hero/image9.png",
  //   alt: "멤버십 혜택 안내",
  //   backgroundColor: "",
  // textColor: "text-gray-900",
  // titleKey: "hero.slides.3.title",
  // subtitleKey: "hero.slides.3.subtitle",
  // descriptionKey: "hero.slides.3.description",
  // buttonTextKey: "hero.slides.3.buttonText",
  // altKey: "hero.slides.3.alt",
  // },
  // {
  //   id: 10,
  //   title: "트렌드 룩북",
  //   subtitle: "스타일링 가이드",
  //   description: "이번 시즌 트렌드 아이템으로 완성하는 퍼펙트 룩",
  //   buttonText: "룩북 보기",
  //   buttonLink: "/category/lookbook",
  //   image: "/hero/image10.png",
  //   alt: "트렌드 룩북 스타일링",
  //   backgroundColor: "",
  // textColor: "text-gray-900",
  // titleKey: "hero.slides.4.title",
  // subtitleKey: "hero.slides.4.subtitle",
  // descriptionKey: "hero.slides.4.description",
  // buttonTextKey: "hero.slides.4.buttonText",
  // altKey: "hero.slides.4.alt",
  // },
  // {
  //   id: 11,
  //   title: "브랜드 스토리",
  //   subtitle: "보고핏의 철학",
  //   description: "건강한 라이프스타일을 위한 프리미엄 스포츠웨어",
  //   buttonText: "브랜드 알아보기",
  //   buttonLink: "/about",
  //   image: "/hero/image11.png",
  //   alt: "보고핏 브랜드 스토리",
  //   backgroundColor: "",
  // textColor: "text-gray-900",
  // titleKey: "hero.slides.5.title",
  // subtitleKey: "hero.slides.5.subtitle",
  // descriptionKey: "hero.slides.5.description",
  // buttonTextKey: "hero.slides.5.buttonText",
  // altKey: "hero.slides.5.alt",
  // },
  // {
  //   id: 12,
  //   title: "AI 피팅 서비스",
  //   subtitle: "가상 착용 체험",
  //   description: "AI로 미리 입어보고 완벽한 사이즈를 찾아보세요",
  //   buttonText: "가상 피팅하기",
  //   buttonLink: "/virtual-fitting",
  //   image: "/hero/image12.png",
  //   alt: "AI 가상 피팅 서비스",
  //   backgroundColor: "",
  // textColor: "text-gray-900",
  // titleKey: "hero.slides.6.title",
  // subtitleKey: "hero.slides.6.subtitle",
  // descriptionKey: "hero.slides.6.description",
  // buttonTextKey: "hero.slides.6.buttonText",
  // altKey: "hero.slides.6.alt",
  // },
];

// 이미지 프리로드용 별도 배열
export const heroImageUrls = heroBannerSlides.map((slide) => slide.image);